services:
  postgres:
    image: postgres:15.3
    container_name: yagfi-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: 'idk_user'
      POSTGRES_PASSWORD: 'SomeUselessPassword02'
      POSTGRES_DB: 'uj'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'
    networks:
      - yagfi-net

  backend:
    image: regyl/yagfi-back:latest
    container_name: yagfi-back
    restart: unless-stopped
    depends_on:
      - postgres
      - cdxgen-0
      - cdxgen-1
      - cdxgen-2
      - cdxgen-3
      - cdxgen-4
    environment:
      APP_HOST_NAME: 'postgres'
      GithubBearer: ${GITHUB_BEARER}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    ports:
      - '8080:8080'
    networks:
      - yagfi-net

  frontend:
    image: regyl/yagfi-front:latest
    container_name: yagfi-front
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: 'http://yagfi.com:8080/api'
    ports:
      - '80:80'
    networks:
      - yagfi-net

  cdxgen-0:
    image: ghcr.io/cyclonedx/cdxgen:v11.11.0
    container_name: cdxgen-0
    ports:
      - '127.0.0.1:9090:9090'
    environment:
      CDXGEN_DEBUG_MODE: "debug"
    networks:
      - yagfi-net
    command: >
      cdxgen
      --no-babel
      --server
      --server-host 0.0.0.0
      --server-port 9090
  cdxgen-1:
    image: ghcr.io/cyclonedx/cdxgen:v11.11.0
    container_name: cdxgen-1
    ports:
      - '127.0.0.1:9091:9091'
    environment:
      CDXGEN_DEBUG_MODE: "debug"
    networks:
      - yagfi-net
    command: >
      cdxgen
      --no-babel
      --server
      --server-host 0.0.0.0
      --server-port 9091
  cdxgen-2:
    image: ghcr.io/cyclonedx/cdxgen:v11.11.0
    container_name: cdxgen-2
    ports:
      - '127.0.0.1:9092:9092'
    environment:
      CDXGEN_DEBUG_MODE: "debug"
    networks:
      - yagfi-net
    command: >
      cdxgen
      --no-babel
      --server
      --server-host 0.0.0.0
      --server-port 9092
  cdxgen-3:
    image: ghcr.io/cyclonedx/cdxgen:v11.11.0
    container_name: cdxgen-3
    ports:
      - '127.0.0.1:9093:9093'
    environment:
      CDXGEN_DEBUG_MODE: "debug"
    networks:
      - yagfi-net
    command: >
      cdxgen
      --no-babel
      --server
      --server-host 0.0.0.0
      --server-port 9093
  cdxgen-4:
    image: ghcr.io/cyclonedx/cdxgen:v11.11.0
    container_name: cdxgen-4
    ports:
      - '127.0.0.1:9094:9094'
    environment:
      CDXGEN_DEBUG_MODE: "debug"
    networks:
      - yagfi-net
    command: >
      cdxgen
      --no-babel
      --server
      --server-host 0.0.0.0
      --server-port 9094

volumes:
  postgres_data:

networks:
  yagfi-net:
    driver: bridge
