services:
  postgres:
    image: postgres:15.3
    container_name: yagfi-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: 'idk_user'
      POSTGRES_PASSWORD: 'SomeUselessPassword02'
      POSTGRES_DB: 'uj'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - yagfi-net

  backend:
    image: regyl/yagfi-back:latest
    container_name: yagfi-back
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      APP_HOST_NAME: 'postgres'
      GithubBearer: '<github token>'
    ports:
      - '8080:8080'
    networks:
      - yagfi-net

  frontend:
    image: regyl/yagfi-front:latest
    container_name: yagfi-front
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: 'http://yagfi.com:8080/api/issues'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    networks:
      - yagfi-net
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: yagfi-certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - yagfi-network

volumes:
  postgres_data:

networks:
  yagfi-net:
    driver: bridge
